apiVersion: v1
kind: Service
metadata:
  name: {{ include "trip-analyzer.fullname" . }}
  labels:
    {{- include "trip-analyzer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trip-analyzer.selectorLabels" . | nindent 4 }}