{{- if .Values.externalSecretsEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "data-web-client.fullname" . }}-nats-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-web-client.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName | default "gcpsm-secret-store" }}
    kind: {{ .Values.externalSecrets.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ include "data-web-client.fullname" . }}-nats-secret
    template:
      engineVersion: v2
      data:
        NATS_USER: "{{ "{{ .natsUser }}" }}"
        NATS_PASSWORD: "{{ "{{ .natsPassword }}" }}"
        NATS_SCORING_PASSWORD: "{{ "{{ .natsConnectorPassword }}" }}"
  data:
    - secretKey: natsUser
      remoteRef:
        key: {{ .Values.externalSecrets.natsUserSecretName | default "NATS_SERVER_USER" }}
    - secretKey: natsPassword
      remoteRef:
        key: {{ .Values.externalSecrets.natsPasswordSecretName | default "NATS_SERVER_PASSWORD" }}
    - secretKey: natsConnectorPassword
      remoteRef:
        key: NATS_CONNECTOR_PASSWORD
{{- end }}
