{{- if eq .Values.pkiStrategy "remote" }}
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: {{ include "data-web-client.fullname" . }}-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-web-client.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
