{{- if .Values.externalSecretsEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-ksa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "data-web-client.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.externalSecrets.gcpServiceAccount | quote }}
{{- end }}
