{{- if .Values.externalSecretsEnabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStoreName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: nats-bigtable-connector
spec:
  provider:
    gcpsm:
      projectID: {{ .Values.gcp.projectId | quote }}
      auth:
        workloadIdentity:
          clusterLocation: {{ .Values.externalSecrets.clusterLocation | default "us-central1" }}
          clusterName: {{ .Values.externalSecrets.clusterName | default "sandbox-gke" }}
          serviceAccountRef:
            name: {{ .Values.externalSecrets.serviceAccountName | default "external-secrets-ksa" }}
{{- end }}
