services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    # add --debug for Debug-Level Logging
    # add --V for Trace-Level Logging
    command: ["-m", "8222", "--debug", "-V"]

  subscriber:
    build:
      context: ../../
      dockerfile: tools/nats-subscriber/Dockerfile
    depends_on:
      - nats
