; PlatformIO Project Configuration
; Nexus SDV IoT Client - ESP32 Telemetry Firmware
;
; Build:    pio run
; Upload:   pio run -t upload
; Monitor:  pio device monitor
; FS:       pio run -t uploadfs

[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    nanopb/Nanopb@^0.4.9
    mikalhart/TinyGPSPlus@^1.0.3
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DPB_FIELD_32BIT=1

[env:esp32dev]
platform = espressif32
board = esp32dev

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1

[env:esp32_d1_mini]
platform = espressif32
board = wemos_d1_mini32
