apiVersion: v1
kind: Secret
metadata:
  name: factory-helper-tls
type: Opaque
stringData:
  server.crt.pem: {{ .Values.certificates.serverCert | quote }}
  server.key.pem: {{ .Values.certificates.serverKey | quote }}
  keycloak-ca.pem: {{ .Values.certificates.keycloakCa | quote }}
