import argparse
import asyncio
import os

import device
import factory

DEFAULT_OPERATIONAL_PATH = "certificates/"
DEFAULT_PKI_STRATEGY = "local"
DEFAULT_REGISTRATION_URL = "https://localhost:8080"
BOOTSTRAP_ENV_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "..", "..", "iac", "bootstrapping", ".bootstrap_env"
)


def load_bootstrap_env():
    if not os.path.isfile(BOOTSTRAP_ENV_PATH):
        return {}
    env = {}
    with open(BOOTSTRAP_ENV_PATH) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, value = line.partition("=")
            env[key.strip()] = value.strip().strip('"').strip("'")
    return env


def parse_args():
    bootstrap = load_bootstrap_env()

    pki_strategy = bootstrap.get("PKI_STRATEGY", DEFAULT_PKI_STRATEGY)
    registration_hostname = bootstrap.get("REGISTRATION_HOSTNAME")
    registration_url = (
        f"https://{registration_hostname}:8080"
        if registration_hostname
        else DEFAULT_REGISTRATION_URL
    )

    parser = argparse.ArgumentParser(
        description="Device client for SDV telemetry system"
    )
    parser.add_argument(
        "-uid",
        required=True,
        help="device identifier",
    )
    parser.add_argument(
        "-pki_strategy",
        default=pki_strategy,
        choices=["local", "remote"],
        help="PKI strategy: 'local' or 'remote'",
    )
    parser.add_argument(
        "-factory-cert",
        default=None,
        help="Path to factory certificate chain (PEM). Defaults to vehicle-<uid>-factory[-gcp]-chain.pem",
    )
    parser.add_argument(
        "-factory-key",
        default=None,
        help="Path to factory private key (PEM). Defaults to vehicle-<uid>-factory[-gcp]-key.pem",
    )
    parser.add_argument(
        "-registration-url",
        default=registration_url,
        help="Registration server URL (e.g., https://registration.example.com:8080)",
    )
    parser.add_argument(
        "-output",
        type=str,
        default=DEFAULT_OPERATIONAL_PATH,
        help="Output directory path for the generated operation key and certificate",
    )
    parser.add_argument(
        "-with-telemetry",
        action="store_true",
        default=False,
        help="Also sends fake telemetry data",
    )
    parser.add_argument(
        "-interval",
        type=int,
        default=5,
        help="Telemetry interval in seconds (default: 5)",
    )
    args = parser.parse_args()

    gcp_suffix = "-gcp" if args.pki_strategy == "remote" else ""
    if args.factory_cert is None:
        args.factory_cert = f"vehicle-{args.uid}-factory{gcp_suffix}-chain.pem"
    if args.factory_key is None:
        args.factory_key = f"vehicle-{args.uid}-factory{gcp_suffix}-key.pem"

    return args


def main():
    args = parse_args()

    print(f"Starting device registration for uid: {args.uid}")
    print(f"PKI Strategy: {args.pki_strategy}")
    print(f"Registration server: {args.registration_url}")
    print(f"Output directory for operational files: {args.output}")
    print()

    # Use factory certificate provided via CLI (already generated by shell script)
    client_key_path, client_csr_path, client_certificate_path = factory.prepare_factory_cert(
        args.vin,
        args.factory_cert,
        args.factory_key,
    )

    # Register and get operational certificate (generates new operational key)
    keycloak_server_url, nats_server_url = device.register(
        args.vin,
        args.pki_strategy,
        client_key_path,
        client_csr_path,
        client_certificate_path,
        args.registration_url,
        args.output,
    )

    if args.with_telemetry:
        # Authenticate with Keycloak using operational certificate + operational key
        access_token, expires_in = device.get_access_token(
            keycloak_server_url,
            args.output,
        )

        asyncio.run(device.send_data(args.vin, args.interval, nats_server_url, access_token))


if __name__ == "__main__":
    main()
