import argparse
import asyncio

import device
import factory

OPERATIONAL_PATH = "certificates/"

def parse_args():
    parser = argparse.ArgumentParser(
        description="Device client for SDV telemetry system"
    )
    parser.add_argument(
        "-uid",
        required=True,
        help="device identifier",
    )
    parser.add_argument(
        "-pki_strategy",
        required=True,
        choices=["local", "remote"],
        help="PKI strategy: 'local' or 'remote'",
    )
    parser.add_argument(
        "-factory-cert",
        required=True,
        help="Path to factory certificate chain (PEM)",
    )
    parser.add_argument(
        "-factory-key",
        required=True,
        help="Path to factory private key (PEM)",
    )
    parser.add_argument(
        "-registration-url",
        required=True,
        help="Registration server URL (e.g., https://registration.example.com:8080)",
    )
    parser.add_argument(
        "-output",
        type=str,
        default=OPERATIONAL_PATH,
        help="Output directory path for the generated operation key and certificate",
    )
    parser.add_argument(
        "-with-telemetry",
        action="store_true",
        default=False,
        help="Also sends fake telemetry data",
    )
    parser.add_argument(
        "-interval",
        type=int,
        default=5,
        help="Telemetry interval in seconds (default: 5)",
    )
    return parser.parse_args()

def main():
    args = parse_args()

    print(f"Starting device registration for uid: {args.uid}")
    print(f"PKI Strategy: {args.pki_strategy}")
    print(f"Registration server: {args.registration_url}")
    print(f"Output directory for operational files: {args.output}")
    print()

    # Use factory certificate provided via CLI (already generated by shell script)
    client_key_path, client_csr_path, client_certificate_path = factory.prepare_factory_cert(
        args.vin,
        args.factory_cert,
        args.factory_key,
    )

    # Register and get operational certificate (generates new operational key)
    keycloak_server_url, nats_server_url = device.register(
        args.vin,
        args.pki_strategy,
        client_key_path,
        client_csr_path,
        client_certificate_path,
        args.registration_url,
        args.output,
    )

    if args.with_telemetry:
        # Authenticate with Keycloak using operational certificate + operational key
        access_token, expires_in = device.get_access_token(
            args.pki_strategy,
            keycloak_server_url,
            args.output,
        )

        asyncio.run(device.send_data(args.vin, args.interval, nats_server_url, access_token))


if __name__ == "__main__":
    main()
