#ifndef CERT_MANAGER_H
#define CERT_MANAGER_H

#include <stdbool.h>
#include <stddef.h>

// Initialize LittleFS and verify factory certs exist.
bool cert_manager_init();

// Load a PEM file from LittleFS into a heap-allocated null-terminated buffer.
// Caller must free() the returned pointer.
char *cert_load_pem(const char *path);

// Generate RSA-2048 operational keypair.
// Writes PEM-encoded private key into *key_pem (heap-allocated, caller frees).
// Note: Takes 15-60 seconds on ESP32.
bool cert_generate_operational_keypair(char **key_pem, size_t *key_pem_len);

// Create a PEM-encoded CSR with CN="VIN:{vin} DEVICE:{vin}", O="Vehicle Manufacturer".
// key_pem: PEM-encoded private key generated by cert_generate_operational_keypair.
// Writes PEM-encoded CSR into *csr_pem (heap-allocated, caller frees).
bool cert_create_csr(const char *vin, const char *key_pem,
                     char **csr_pem, size_t *csr_pem_len);

// Save operational certificate and key to LittleFS for persistence across reboots.
bool cert_save_operational(const char *cert_pem, const char *key_pem);

// Check if an operational certificate already exists on the filesystem.
bool cert_has_operational();

#endif
