# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: scoring-message.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto


@dataclass(eq=False, repr=False)
class ScoringMessage(betterproto.Message):
    vehicle_id: str = betterproto.string_field(1)
    score: str = betterproto.string_field(2)
    suggestions: str = betterproto.string_field(3)
