apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "data-converter.fullname" . }}
  labels:
    {{- include "data-converter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "data-converter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "data-converter.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CONFIG_PATH
              value: /etc/data-converter/config.yaml
          envFrom:
            - secretRef:
                name: {{ include "data-converter.fullname" . }}-credentials
          volumeMounts:
            - name: config
              mountPath: /etc/data-converter
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "data-converter.fullname" . }}-config
