apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-converter.fullname" . }}-credentials
  labels:
    {{- include "data-converter.labels" . | nindent 4 }}
type: Opaque
stringData:
  NATS_USER: {{ .Values.secrets.natsUser | quote }}
  NATS_PASSWORD: {{ .Values.secrets.natsPassword | quote }}
  MQTT_USER: {{ .Values.secrets.mqttUser | quote }}
  MQTT_PASS: {{ .Values.secrets.mqttPassword | quote }}
